/// Use Case: Add Expense
/// 
/// Domain layer use case responsible for adding new expenses to the system.
/// Follows Clean Architecture principles by encapsulating business logic
/// and coordinating with the repository layer for data persistence.
/// 
/// Key Responsibilities:
/// - Validate business rules for expense creation
/// - Coordinate with repository for data persistence
/// - Maintain separation between domain and data layers
/// - Provide a clean interface for presentation layer
/// 
/// Business Rules Enforced:
/// - Expense must have valid required fields
/// - Amount should be positive (validated at repository level)
/// - Unique ID generation is handled by repository
/// 
/// Usage:
/// ```dart
/// final addExpense = AddExpense(repository);
/// await addExpense(newExpense);
/// ```

import '../entities/expense.dart';
import '../repositories/expense_repository.dart';

/// Use case for adding new expenses to the system
/// 
/// This use case encapsulates the business logic for creating and storing
/// new expense records. It acts as an intermediary between the presentation
/// layer and the repository, ensuring proper separation of concerns.
/// 
/// The use case follows the Single Responsibility Principle by focusing
/// solely on expense addition logic and delegating data persistence
/// to the repository layer.
class AddExpense {
  /// Repository dependency for data persistence operations
  final ExpenseRepository repository;

  /// Creates an AddExpense use case with the required repository dependency
  /// 
  /// [repository] The expense repository for data operations
  AddExpense(this.repository);

  /// Adds a new expense to the system
  /// 
  /// Validates the expense data and delegates to the repository for persistence.
  /// The repository is responsible for generating unique IDs and handling
  /// storage-specific operations.
  /// 
  /// [expense] The expense entity to be added to the system
  /// 
  /// Throws:
  /// - [Exception] if the expense data is invalid
  /// - [Exception] if the storage operation fails
  /// 
  /// Example:
  /// ```dart
  /// final expense = Expense(
  ///   id: '', // Will be generated by repository
  ///   title: 'Coffee',
  ///   amount: 150.0,
  ///   category: 'Food',
  ///   date: DateTime.now(),
  /// );
  /// await addExpense(expense);
  /// ```
  Future<void> call(Expense expense) async {
    return await repository.addExpense(expense);
  }
}
